use_frameworks!

target 'FPBitcoinkit_Example' do
  pod 'FPBitcoinkit', :path => '../'

  target 'FPBitcoinkit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
